"""init

Revision ID: e53a0ed9a7e5
Revises: 
Create Date: 2018-08-07 11:50:57.035778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e53a0ed9a7e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=True),
    sa.Column('is_disable', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('company',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('logo', sa.String(length=128), nullable=True),
    sa.Column('website', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('welfare', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.create_index(op.f('ix_company_phone'), 'company', ['phone'], unique=False)
    op.create_table('resume',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('degree', sa.String(length=32), nullable=True),
    sa.Column('job', sa.String(length=64), nullable=True),
    sa.Column('work_year', sa.SmallInteger(), nullable=True),
    sa.Column('resume_url', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_degree'), 'resume', ['degree'], unique=False)
    op.create_index(op.f('ix_resume_job'), 'resume', ['job'], unique=False)
    op.create_index(op.f('ix_resume_name'), 'resume', ['name'], unique=False)
    op.create_index(op.f('ix_resume_phone'), 'resume', ['phone'], unique=False)
    op.create_index(op.f('ix_resume_work_year'), 'resume', ['work_year'], unique=False)
    op.create_table('job',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('degree', sa.String(length=32), nullable=True),
    sa.Column('work_year', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.String(length=20), nullable=True),
    sa.Column('is_disable', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_degree'), 'job', ['degree'], unique=False)
    op.create_index(op.f('ix_job_name'), 'job', ['name'], unique=True)
    op.create_index(op.f('ix_job_work_year'), 'job', ['work_year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_work_year'), table_name='job')
    op.drop_index(op.f('ix_job_name'), table_name='job')
    op.drop_index(op.f('ix_job_degree'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_resume_work_year'), table_name='resume')
    op.drop_index(op.f('ix_resume_phone'), table_name='resume')
    op.drop_index(op.f('ix_resume_name'), table_name='resume')
    op.drop_index(op.f('ix_resume_job'), table_name='resume')
    op.drop_index(op.f('ix_resume_degree'), table_name='resume')
    op.drop_table('resume')
    op.drop_index(op.f('ix_company_phone'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
